name_to_key = "input"


inputs_movement_test = {
    name_to_key + "0": {
        "first_line": "10 10",
        "second_line": "FFFFFFFFFDFFFFFFFFFDFFFFFFFFFDFFFFFFFFF",
        "expected_output": "O 0 0"
    },
    name_to_key + "1": {
        "first_line": "5 5",
        "second_line": "FDFEFDFEFDFEFDF",
        "expected_output": "L 4 4"
    },
    name_to_key + "2": {
        "first_line": "1232 1232",
        "second_line": "",
        "expected_output": "N 0 0",
    },
    name_to_key + "3": {
        "first_line": "",
        "second_line": "TTTTTTTTTTTTT",
        "expected_output": "",
    },
    name_to_key + "4": {
        "first_line": "15 36",
        "second_line": "FFFFFFFFFFFFFFFFDFETTTTTTTTTTTTTTTT",
        "expected_output": "N 1 0",
    },
    name_to_key + "5": {
        "first_line": "50 50",
        "second_line": "TTFFDTTETDEDTTDDFFDEFDTEFTTDDEDEFFTEETEDTTEEDDEFFFTEDFDFTTDDDTTTTTFDEFDFFTEDTEDEFTDTETETFDFTDTFEFDTFTTEEFEEFEDDTFTEDFFTTDTTTFDETETDDTEDDTFEDFDEFDDTTDEFEFTDTTDFFEDDTDFDETTDDFFTEEDFFTTTDETFTFDTETTTTDEFFETFTDFDTEEDFTEFTEFFFTDEEDDTTEFDFETDFEEETTDFTTTEEEEEDTETFETTETDEEFTTDDDFFTFDDEFDEFTTTEDFFFTEEDTDDTTDFDEETTDETETDDETTTDEFEETTETDEDTEFTTDDEEFDFDTEEEDEDTDDTEEEEEDTFEDEDDDTTTFFDETFFDDTFDTEFFFDDFEEFEFDDFDTTETTDTDTTTDEDFTTDDDTTTTTDTEDFEFDTFFETEEEFFFEFDTTDETTFFETTDEETFEDTEFFDEEFEEDTTFFTEEETDTEEEFTFFEFEFDFFEFTFEDEEDFDDDFDFEFEDDDTEETTETFTTFDTDEFTFEEDEFTEFETFEEEFDETEDFFTFDFFTFDTFEFDEDTTTFEDEFTTDDEEFDTFTEEDTETEFEFFEEEFFTFEETEDDFFFTFDETFDEFETDTFDDFFTFDTFTTFTTFDFDDEDEFFFETTTTFFFFTDEEEFTDFDDFTFETDDEDFFFEFFDDDTTDEFETFDEFDEDETDFEETEDTFETTTFEEEFTETFFTDFDFEDFTDDTEFTFFEFEEFTTTFEEFTDDDEEDTFTFDTTDFDEETFFTDFDEDEEFFDTFETEDEETTEFFFDETTTFTEETFDTEFFEEFFDEDFFDTTEFDETDDETDDDTDFETTTETEEEFDFTEETDTEDETTEDETFEEEFTFFEEDTFFFTEDDFDDFDDTTEDEETETEEFDDDTTTTTEEFEFFFTEFEDEFEFEFEDDFFEEEFEETTFDFEEDDTTTTETDTEDEFFDFTTFFTDTEDEDEDDFEFT",
        "expected_output": "S 11 13",
    },
    name_to_key + "6": {
        "first_line": "1000 1000",
        "second_line": "EDFFEDFTTEDFTETEFDTFDTDTDTFDFTDEDTFFTFTDDDETFTFEFETEFEEEDFTTEFEEDFTFFTFTDTTDFDDDTFTTTDDEETDDFTDFFETTDTTTFEEFFTDTFETDEFEDEFDFDTTEFDEEDTTDDETTDEDTTEEEFFEEDDDETDFDTEDEDFTFFEEDEDDFEDEDFDDFEDEETTFTETFTTTEETTFDDTTEFDDEDTDEDEDDFTFEFTDFEFFDTETFFFTDTFTEFFFEDETFETTFETDFFFDEETETFEFFTFETFEFFTEETDETDEFEFTFDEEFDEEDTEDEFEFTEETTTTFEEFTDTDDFDEDFEDDDDTEDDDTFDDDEEEEDTTDFEDTDETFTFTFDFTFTDFEDEFDEEEDDETEEEDDTEFEFFFDTEFTFFEETETEDDDDEFTEEDDEDDTTDTTEDFEFETFTDTFTFEEDEFEDTEFDEEDEDEFDTEDEETEDEDEDDEDTDTDDFFEFDEETTEDDEFFTFDEFEFFDFDDTFEFTTDDDTDTDDFDEEDETDDDFEFTEDEFEEFDETEFTDFTFDDFTFEEDEEEEEDDDTEDDFTDFDFFFDTETTTDETTEDETEDDETETDEEFTTFTDDFDEEEFFDEDTEDFTEETTEFDDFTFEFEEEETFTEFTEDFTFFEEEDFDETTEFDTFFDDDFFDTEEFETDTETFDFTDEDTFFFFEETTFDFDDFTDTTDFFTFDDDTDTDDFDDEETETTFETTEFDTTFEDDFDTEDETTTEDTDEFFEFFFTDTEDTTTEFFTTTTDFTDFTETDDFDEEFEFTEFTTDDDTEFEFETDDDDTETTTETEEDEETTDDFTDTETTFTFFTEFFEEDEEEFTTDEEEEFEDTEEEDEEDDDTETEFEFDDDEDEFEFTTDFDTTDEDFTFDDTDTFDDDDEFEEEDEDDTTTDDTEDTEDDTDTDDTFETDTDTDFDDDTTEEEFEDTEFFDEEDTTEFTDEDTDDETEFEFEFFTTTEEFDEF",
        "expected_output": "L 25 5",
    },
}


if __name__ == "__main__":
    print(inputs_movement_test["input1"]["first_line"])  # 10 10